# const.py

# bonuses
YATZY_BONUS = 50
UPPER_BONUS = 50
FULL_HOUSE_BONUS = None # use number, if sum should not be counted from dices
SMALL_STRAIGHT_BONUS = 15
LARGE_STRAIGHT_BONUS = 20
UPPER_BONUS_THRESHOLD = 63

# categories
CHANGE = 0
YATZY = 1
FULLHOUSE = 2
SMALLSTRAIGHT = 3
LARGESTRAIGHT = 4
PAIR = 5
ONE = 6
TWO = 7
THREE = 8
FOUR = 9
FIVE = 10
SIX = 11
DOUBLE = 12
TRIPLE = 13
QUADRUPLE = 14
